#include "header.h"

char *tokens[MAX_TOKENS];
char **allLines;
int lineCount = 0;
int tokenCount = 0;
char str[N];
int cur = 0;
//              //123456789012345 6
char spChars[] = "+*-,[](){}:#.=/\\";
char **identifierNames;
Id **identifierAttributes;
int identifierCount = 0;
int indentation=0;

char *matlangKeyWords[] = {
        "for", "scalar", "matrix", "vector", "print", "choose", "sqrt", "tr", "in","printsep"
};

int matlangKeywordCount = LEN(matlangKeyWords);
int spCharCount = LEN(spChars);

//char *matMulOp = "\\M";//binary matrix multiplication
//char *matAddOp = "\\A";//binary matrix addition
//char *matSubOp = "\\S";//binary matrix subtraction
//char *scMatOp = "\\E";//(expr1 is scalar,expr2 is matrix)
//char *matScOp = "\\e";//binary operator evaluating to a matrix. postfix: expr1 expr2 \e
//char *matTpOp = "\\T";//unary operator evaluating to a matrix.postfix: expr1 \T
//char *matIndexOp = "\\I";//ternary operator evaluating to a dereferenced entry of a matrix. in postfix: id expr1 exp2 \I
//char *vecIndexOp = "\\i";//binary operator evaluating to a dereferenced entry of a vector. in postfix: id expr1 \i
//char *chooseOp = "\\c";//quaternary operator evaluating to a scalar. in postfix: expr1 expr2 expr3 expr4 \c
//char *sqrtOp = "\\r";//unary operator evaluating to a scalar. in postfix: expr1 \r

#pragma region copy
char* copy1=
        "#include \"stdlib.h\"\n"
        "#include \"math.h\"\n"
        "#include \"string.h\"\n"
        "#include \"stdio.h\"\n"
        "#include \"stddef.h\"\n"
        "\n"
        "typedef struct Matrix {\n"
        "    int m, n;\n"
        "    float **value;\n"
        "} Matrix;\n"
        "\n"
        "void matrixInit(Matrix *m) {\n"
        "    int i, j;\n"
        "    m->value = (float **) malloc(sizeof(float *) * (m->m));\n"
        "    for (i = 0; i < m->m; i++) {\n"
        "        m->value[i] = (float *) malloc(sizeof(float) * (m->n));\n"
        "        for (j = 0; j < m->n; j++) {\n"
        "            m->value[i][j] = 0;\n"
        "        }\n"
        "    }\n"
        "}\n"
        "\n"
        "Matrix *matrixSub(Matrix *a, Matrix *b) {\n"
        "    int m = a->m, n = a->n, i, j;\n"
        "    Matrix *res = (Matrix *) malloc(sizeof(Matrix));\n"
        "    res->m = m;\n"
        "    res->n = n;\n"
        "    matrixInit(res);\n"
        "    for (i = 0; i < m; i++) {\n"
        "        for (j = 0; j < n; j++) {\n"
        "            res->value[i][j] = a->value[i][j] - b->value[i][j];\n"
        "        }\n"
        "    }\n"
        "    return res;\n"
        "}\n"
        "\n"
        "Matrix *matrixAdd(Matrix *a, Matrix *b) {\n"
        "    int m = a->m, n = a->n, i, j;\n"
        "    Matrix *res = (Matrix *) malloc(sizeof(Matrix));\n"
        "    res->m = m;\n"
        "    res->n = n;\n"
        "    matrixInit(res);\n"
        "    for (i = 0; i < m; i++) {\n"
        "        for (j = 0; j < n; j++) {\n"
        "            res->value[i][j] = a->value[i][j] + b->value[i][j];\n"
        "        }\n"
        "    }\n"
        "    return res;\n"
        "}\n"
        "\n"
        "Matrix *matMul(Matrix *a, Matrix *b) {\n"
        "    int m = a->m, n = b->n, o = a->n, i, j, k;\n"
        "    Matrix *res = (Matrix *) malloc(sizeof(Matrix));\n"
        "    res->m = m;\n"
        "    res->n = n;\n"
        "    matrixInit(res);\n"
        "    for (i = 0; i < m; i++) {\n"
        "        for (j = 0; j < n; j++) {\n"
        "            for (k = 0; k < o; k++) {\n"
        "                res->value[i][j] += a->value[i][k] * b->value[k][j];\n"
        "            }\n"
        "        }\n"
        "    }\n"
        "    return res;\n"
        "}\n"
        "\n"
        "Matrix *matScMul(Matrix *a, float sc) {\n"
        "    int m = a->m, n = a->n, i, j;\n"
        "    Matrix *res = (Matrix *) malloc(sizeof(Matrix));\n"
        "    res->m = m;\n"
        "    res->n = n;\n"
        "    matrixInit(res);\n"
        "    for (i = 0; i < m; i++) {\n"
        "        for (j = 0; j < n; j++) {\n"
        "            res->value[i][j] = a->value[i][j] * sc;\n"
        "        }\n"
        "    }\n"
        "    return res;\n"
        "}\n"
        "\n"
        "Matrix *scMatMul(float sc, Matrix *a) {\n"
        "    return matScMul(a, sc);\n"
        "}\n"
        "\n"
        "void assignMM(Matrix *lhs, Matrix *rhs) {\n"
        "    int m = lhs->m, n = lhs->n, i, j;\n"
        "    for (i = 0; i < m; i++) {\n"
        "        for (j = 0; j < n; j++) {\n"
        "            lhs->value[i][j] = rhs->value[i][j];\n"
        "        }\n"
        "    }\n"
        "}\n"
        "\n"
        "void assignML(Matrix *lhs, char *floatList) {\n"
        "\n"
        "    int m = lhs->m, n = lhs->n, i, j, k = 0;\n"
        "    char *floatString;\n"
        "\n"
        "    char *mallocced = (char *) malloc((strlen(floatList) + 1) * sizeof(char));\n"
        "    strcpy(mallocced, floatList);\n"
        "    char **flp = &mallocced;\n"
        "\n"
        "    char *floatTokens[m * n];\n"
        "    for (i = 0; i < m * n; i++) {\n"
        "        if ((floatString = strtok_r(mallocced, \" \", flp)) != NULL) {\n"
        "            floatTokens[j++] = floatString;\n"
        "        }\n"
        "    }\n"
        "\n"
        "    for (i = 0; i < m; i++) {\n"
        "        for (j = 0; j < n; j++) {\n"
        "            lhs->value[i][j] = atof(floatTokens[k++]);\n"
        "        }\n"
        "    }\n"
        "}\n"
        "\n"
        "Matrix *trM(Matrix *a) {\n"
        "    int m = a->m, n = a->n, i, j;\n"
        "    Matrix *res = (Matrix *) malloc(sizeof(Matrix));\n"
        "    res->m = n;\n"
        "    res->n = m;\n"
        "    matrixInit(res);\n"
        "    for (i = 0; i < m; i++) {\n"
        "        for (j = 0; j < n; j++) {\n"
        "            res->value[j][i] = a->value[i][j];\n"
        "        }\n"
        "    }\n"
        "    return res;\n"
        "}\n"
        "\n"
        "float trS(float a) {\n"
        "    return a;\n"
        "}\n"
        "\n"
        "float choose(float selector, float zero, float pos, float neg) {\n"
        "    return selector ? (selector > 0 ? pos : neg) : zero;\n"
        "}\n"
        "\n"
        "void printsep() {\n"
        "    //            0123456789012\n"
        "    char sep[] = \"-------------\\n\";\n"
        "    printf(\"%s\", sep);\n"
        "}\n"
        "\n"
        "void floatToStr(char *dest, float f) {\n"
        "    if ((int) f == f) {\n"
        "        sprintf(dest, \"%d\", (int) f);\n"
        "    } else {\n"
        "        sprintf(dest, \"%f\", f);\n"
        "    }\n"
        "}\n"
        "\n"
        "void printS(float s) {\n"
        "    char floatStr[9];\n"
        "    floatToStr(floatStr, s);\n"
        "    printf(\"%s\\n\", floatStr);\n"
        "}\n"
        "\n"
        "void printM(Matrix *a) {\n"
        "    int n = a->n, m = a->m, i, j;\n"
        "    char *out = (char *) malloc((m * n * 12 + n + 50) * sizeof(char));\n"
        "    char *beginning;\n"
        "    out[0] = 0;\n"
        "    beginning = out;\n"
        "    char step[12];\n"
        "    for (i = 0; i < m; i++) {\n"
        "        for (j = 0; j < n; j++) {\n"
        "            floatToStr(step, a->value[i][j]);\n"
        "            out += sprintf(out, \"%12s\", step);\n"
        "        }\n"
        "        out += sprintf(out, \"\\n\");\n"
        "    }\n"
        "    printf(\"%s\", beginning);\n"
        "}\n"
        "\n"
        "float scAdd(float a, float b) {\n"
        "    return a + b;\n"
        "}\n"
        "\n"
        "float scSub(float a, float b) {\n"
        "    return a - b;\n"
        "}\n"
        "\n"
        "int main() {\n"
        "//start appending here\n"
        "\n"
        "";;
#pragma endregion

